package by.epamtc.stanislavmelnikov.controller.commandenum;

public enum CommandName {
    HOME,
    TOURS,
    SIGN_IN,
    SIGN_OUT,
    REGISTRATION,
    FULL_TOUR_INFO,
    HOTELS,
    FULL_HOTEL_INFO,
    ADD_FEEDBACK,
    FEEDBACKS,
    PERSONAL_DATA,
    RESORTS,
    LOCATION_AJAX,
    CHANGE_PERSONAL_DATA,
    UPDATE_USER,
    REMOVE_FEEDBACK,
    REMOVE_HOTEL,
    ADD_TOUR,
    REMOVE_TOUR,
    CHANGE_TOUR,
    ADD_HOTEL,
    CHANGE_HOTEL,
    ADD_ORDER,
    ORDERS,
    FULL_ORDER_INFO,
    REMOVE_ORDER,
    USERS,
    FULL_USER_INFO,
    ADD_USER,
    REMOVE_USER,
    RESET_PASSWORD,
    ADD_NEW_ROLE,
    GIVE_ADMIN_RIGHTS,
    BLOCK_USER
}

